name: cbm
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.7.4
  - anyio=2.2.0
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.38.0
  - atk-1.0=2.36.0
  - attrs=20.3.0
  - azure-common=1.1.27
  - azure-core=1.12.0
  - azure-storage-blob=12.8.1
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bleach=3.3.0
  - blinker=1.4
  - boost=1.74.0
  - boost-cpp=1.74.0
  - boto=2.49.0
  - boto3=1.17.56
  - botocore=1.20.56
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.1
  - cairo=1.16.0
  - cairomm=1.12.2
  - cairomm-1.0=1.12.2
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - colorlog=4.7.2
  - cryptography=3.4.6
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.7.1
  - entrypoints=0.3
  - epoxy=1.5.7
  - expat=2.2.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.6
  - gensim=3.8.3
  - gettext=0.19.8.1
  - glib=2.68.1
  - glib-tools=2.68.1
  - gmp=6.2.1
  - gobject-introspection=1.68.0
  - google-api-core=1.26.2
  - google-auth=1.28.0
  - google-cloud-core=1.5.0
  - google-cloud-storage=1.19.0
  - google-crc32c=1.1.2
  - google-resumable-media=1.2.0
  - googleapis-common-protos=1.53.0
  - graph-tool=2.37
  - graphite2=1.3.13
  - grpcio=1.37.0
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - gtk3=3.24.28
  - h5py=3.1.0
  - harfbuzz=2.8.1
  - hdf5=1.10.6
  - hicolor-icon-theme=0.17
  - icu=68.1
  - idna=2.10
  - importlib-metadata=3.7.3
  - ipykernel=5.5.0
  - ipython=7.23.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - isodate=0.6.0
  - jedi=0.18.0
  - jinja2=2.11.3
  - jmespath=0.10.0
  - joblib=1.0.1
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter-packaging=0.7.12
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyter_server=1.4.1
  - jupyterlab=3.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.3.0
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - kneed=0.7.0
  - krb5=1.17.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcrc32c=1.1.1
  - libcups=2.2.12
  - libcurl=7.76.0
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.68.1
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libpq=13.1
  - libprotobuf=3.15.8
  - librsvg=2.50.5
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - msrest=0.6.21
  - multidict=5.1.0
  - mysql-common=8.0.23
  - mysql-libs=8.0.23
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - networkx=2.5.1
  - node2vec=0.3.0
  - notebook=6.2.0
  - nspr=4.30
  - nss=3.62
  - numpy=1.20.1
  - oauthlib=3.0.1
  - olefile=0.46
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.3
  - pandoc=2.12
  - pandocfilters=1.4.2
  - pango=1.48.4
  - parso=0.8.1
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.2
  - pip=21.0.1
  - pixman=0.40.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.17
  - prompt_toolkit=3.0.17
  - protobuf=3.15.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycairo=1.20.0
  - pycparser=2.20
  - pygments=2.8.1
  - pygobject=3.40.1
  - pyjwt=2.0.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - pyzmq=22.0.3
  - qt=5.12.9
  - qtconsole=5.1.0
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - s3transfer=0.4.2
  - scikit-learn=0.24.1
  - scipy=1.6.1
  - seaborn=0.11.1
  - seaborn-base=0.11.1
  - send2trash=1.5.0
  - setuptools=49.6.0
  - sigcpp-2.0=2.10.3
  - six=1.15.0
  - smart_open=5.0.0
  - sniffio=1.2.0
  - sparsehash=2.0.3
  - sqlite=3.34.0
  - statsmodels=0.12.2
  - terminado=0.9.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.59.0
  - traitlets=5.0.5
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.26.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstandard=0.15.2
  - zstd=1.4.9
  - pip:
    - bounded-pool-executor==0.0.3
    - pqdm==0.1.0
